#!/bin/sh
#
# PROVIDE: btfs
# KEYWORD:

. /etc/rc.subr

export BTFS_PATH=/root/.btfs
name="btfs"
rcvar="btfs_enable"
btfs_user="root"
btfs_command="/usr/local/bin/btfs daemon"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${btfs_command}"

load_rc_config $name
: ${btfs_enable:=no}

run_rc_command "$1"